invalidMessage: Los cambios propuestos no cumplen con los elementos mínimos requeridos. Por favor, realiza una revisión de lo realizado, corrigelo y realiza un nuevo commit con los cambios. 
invalidExtensionMessage: Se han agregado o editado archivos que no cumplen con la extensión requerida.  Por favor, realiza una revisión de lo realizado, corrigelo y realiza un nuevo commit con los cambios. 
invalidOperationMessage: Los cambios realizan operaciones sobre los archivos inválidas. Por favor, realiza una revisión de lo realizado, corrigelo y realiza u nuevo commit con los cambios. 
mergeMessage: Cambios aceptados. !Muchas gracias por contribuir! :tada:
validFileExtensions:
- .html
- .png
- .jpg
supportedOperations:
- added
validations:
- type: DOM
  fileExtension: .html
  expectedValues:
  - querySelector: "#titulo"
    attribute: textContent
    exists: true
  - querySelector: "#imagen"
    attribute: src
    exists: true
  - querySelector: "#enlace"
    attribute: href
    exists: true
  - querySelector: "#enlace"
    attribute: textContent
    exists: true
